import { createDbClient } from "../db/client.js";

const db = createDbClient();
await db.connect();

await db.query(`
  CREATE TABLE IF NOT EXISTS public.sets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic text NOT NULL DEFAULT 'Custom Deck',
    title text NOT NULL,
    cards integer NOT NULL DEFAULT 0,
    color text NOT NULL DEFAULT '#FF9B00'
  );
`);

await db.query(`
  CREATE TABLE IF NOT EXISTS public.flashcards (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id integer NOT NULL REFERENCES public.sets(id) ON DELETE CASCADE,
    front text NOT NULL,
    back text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  );
`);

await db.query(`CREATE INDEX IF NOT EXISTS flashcards_set_id_idx ON public.flashcards(set_id);`);

await db.query("UPDATE public.sets SET topic = 'Custom Deck' WHERE topic = 'Custom Set'");

await db.end();

console.log("OK: database setup complete (sets, flashcards, topic normalization).");

