import { createDbClient } from "../db/client.js";

const db = createDbClient();
await db.connect();

await db.query(`
  CREATE TABLE IF NOT EXISTS public.sets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic text NOT NULL DEFAULT 'Custom Deck',
    title text NOT NULL,
    cards integer NOT NULL DEFAULT 0,
    color text NOT NULL DEFAULT '#FF9B00'
  );
`);

await db.query(`
  CREATE TABLE IF NOT EXISTS public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    password text NOT NULL
  );
`);

await db.query(`
  CREATE TABLE IF NOT EXISTS public.subjects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic text NOT NULL DEFAULT 'Custom Deck',
    title text NOT NULL,
    cards integer NOT NULL DEFAULT 0,
    color text NOT NULL DEFAULT '#FF9B00'
  );
`);

await db.query(`
  CREATE TABLE IF NOT EXISTS public.flashcards (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id integer NOT NULL REFERENCES public.sets(id) ON DELETE CASCADE,
    front text NOT NULL,
    back text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  );
`);

await db.query(`CREATE INDEX IF NOT EXISTS flashcards_set_id_idx ON public.flashcards(set_id);`);
await db.query(`CREATE UNIQUE INDEX IF NOT EXISTS users_email_uidx ON public.users(email);`);

await db.query("UPDATE public.sets SET topic = 'Custom Deck' WHERE topic = 'Custom Set'");
await db.query("UPDATE public.subjects SET topic = 'Custom Deck' WHERE topic = 'Custom Set'");

// Backward-compatibility for older users tables where id existed but was not auto-generated.
await db.query(`
  DO $$
  BEGIN
    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'users'
        AND column_name = 'id'
        AND is_identity = 'NO'
    ) THEN
      CREATE SEQUENCE IF NOT EXISTS public.users_id_seq;
      ALTER TABLE public.users
        ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq');
      PERFORM setval(
        'public.users_id_seq',
        COALESCE((SELECT MAX(id) FROM public.users), 0) + 1,
        false
      );
    END IF;
  END$$;
`);

await db.end();

console.log("OK: database setup complete (users, subjects, sets, flashcards).");

